In [52]:
import pandas as pd
import numpy as np

In [67]:
data = pd.read_csv('E:\\备份\\训练数据汇总(8W)\\2019_4_10_drop_duplicate.csv')
data = data.loc[:, ~data.columns.str.contains('^Unnamed')]

In [68]:
data.head()

SCREEN_RESOLUTION_LONG  SCREEN_RESOLUTION_WIDTH  VIDEO_CLARITY  \
0                  1334.0                    750.0              2   
1                  1334.0                    750.0              1   
2                  1334.0                    750.0              1   
3                  1334.0                    750.0              1   
4                  1334.0                    750.0              1   

   VIDEO_BITRATE  INITIAL_DELAY  INITIAL_DELAY_PEAK_RATE  VIDEO_STALLING_NUM  \
0            890              0                  13066.0                   0   
1            534              0                  15360.0                   0   
2            400              0                  11920.0                   0   
3            864              0                  19577.0                   0   
4            833            569                  16647.0                   0   

   VIDEO_STALLING_TOTAL_TIME  VIDEO_TOTAL_TIME  VIDEO_PLAY_TOTAL_TIME  ...    \
0                          0      29722.000122                  30047  ...     
1                          0      29722.000122                  29990  ...     
2                          0      30319.999695                  30891  ...     
3                          0      30959.999084                  31411  ...     
4                          0      29611.000061                  30929  ...     

   PIXEL_NUMBER  BATTERY_LOSS  MEAN_STALLING_DURATION  ALL_DOWCLOAD_BIT  \
0     1000500.0             0                     0.0          26411313   
1     1000500.0             0                     0.0          15834720   
2     1000500.0             0                     0.0          12109272   
3     1000500.0             0                     0.0          26730761   
4     1000500.0             0                     0.0          24650413   

     VIDEO_SIZE  error  USER_SCORE  ELOADING  ESTALLING  EVMOS  
0  2.645258e+07    1.0         4.0       4.0        4.0    4.0  
1  1.587155e+07    1.0         4.0       4.0        4.0    4.0  
2  1.212800e+07    1.0         4.0       4.0        4.0    4.0  
3  2.674944e+07    1.0         4.0       4.0        4.0    4.0  
4  2.466596e+07    1.0         4.0       4.0        4.0    4.0  

[5 rows x 26 columns]

In [6]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

data.qos = data[['SCREEN_RESOLUTION_LONG','SCREEN_RESOLUTION_WIDTH','VIDEO_CLARITY','VIDEO_BITRATE',
              'INITIAL_DELAY','INITIAL_DELAY_PEAK_RATE','VIDEO_STALLING_NUM','VIDEO_STALLING_TOTAL_TIME',
              'VIDEO_TOTAL_TIME','VIDEO_PLAY_TOTAL_TIME','VIDEO_ALL_PEAK_RATE','VIDEO_AVERAGE_RATE',
              'PHONE_ELECTRIC_START','PHONE_ELECTRIC_END','PHONE_VERSION', 'PING_AVG_RTT','PIXEL_NUMBER',
              'BATTERY_LOSS','MEAN_STALLING_DURATION']]
data.target = data[['USER_SCORE','ELOADING','ESTALLING','EVMOS']]
X_train, X_test, y_train, y_test = train_test_split(data.qos, data.target, test_size=0.25, 
                                                    random_state=33)
ss = StandardScaler()
X_train = ss.fit_transform(X_train)
X_test = ss.transform(X_test)

In [35]:
qos = ['SCREEN_RESOLUTION_LONG','SCREEN_RESOLUTION_WIDTH','VIDEO_CLARITY','VIDEO_BITRATE',
        'INITIAL_DELAY','INITIAL_DELAY_PEAK_RATE','VIDEO_STALLING_NUM','VIDEO_STALLING_TOTAL_TIME',
        'VIDEO_TOTAL_TIME','VIDEO_PLAY_TOTAL_TIME','VIDEO_ALL_PEAK_RATE','VIDEO_AVERAGE_RATE',
        'PHONE_ELECTRIC_START','PHONE_ELECTRIC_END','PHONE_VERSION', 'PING_AVG_RTT','PIXEL_NUMBER',
        'BATTERY_LOSS','MEAN_STALLING_DURATION']
target = ['USER_SCORE','ELOADING','ESTALLING','EVMOS']

In [36]:
from sklearn import metrics as mr
mr.mutual_info_score(data.qos['SCREEN_RESOLUTION_LONG'], data.target['USER_SCORE'])

0.026662508230586125

In [37]:
import numpy as np
score = np.zeros(19*4).reshape(19,4)

In [38]:
score[1,1] = 1

In [40]:
for i in range(len(qos)):
    for j in range(len(target)):
        score[i,j] = mr.mutual_info_score(data.qos[qos[i]], data.target[target[j]])

In [53]:
score_1 = score[:,0].tolist()
rank1 = np.argsort(score_1)

score_2 = score[:,1].tolist()
rank2 = np.argsort(score_2)

score_3 = score[:,2].tolist()
rank3 = np.argsort(score_3)

score_4 = score[:,3].tolist()
rank4 = np.argsort(score_4)

In [55]:
rank1

array([18,  7,  6, 13, 14, 17, 12,  2,  1,  0, 16,  3,  8, 11,  4, 15,  9,
        5, 10], dtype=int64)

In [56]:
rank2

array([18,  7,  6,  2, 13, 17, 12, 14,  1,  0, 16,  3,  8, 11, 15,  4,  9,
        5, 10], dtype=int64)

In [57]:
rank3

array([18,  7,  6,  2, 13, 17, 14, 12,  1,  0, 16,  3,  8, 11,  4, 15,  9,
        5, 10], dtype=int64)

In [58]:
rank4

array([18,  7,  6,  2, 13, 14, 17, 12,  1,  0, 16,  3,  8, 11,  4, 15,  9,
        5, 10], dtype=int64)

In [72]:
column = [13, 14, 17, 12,  2,  1,  0, 16,  3,  8, 11,  4, 15,  9,  5, 10]
choosen_feature = [qos[value] for index,value in enumerate(column)]

In [74]:
choosen_feature = choosen_feature + target

In [77]:
data_choosen = data[choosen_feature]

In [78]:
data_choosen.to_csv('E:\\备份\\训练数据汇总(8W)\\2019_4_11_after_feature_selection.csv')